@startuml
title Combined

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(JohnDoe, "John Doe")
System(aserver, "a-server")
System(anotherserver, "another-server")    
Rel_D(JohnDoe, aserver, " ") 
Rel_D(JohnDoe, anotherserver, " ") 
Rel_D(anotherserver, aserver, " ")     
@enduml