@startuml
title Ping_ManualRecordingTest Indirect ping test (Manual)

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System(JohnDoe, "John Doe")
System(anotherserver, "another-server")
System(aserver, "a-server")    
Rel_D(JohnDoe, anotherserver, " ") 
Rel_D(anotherserver, aserver, " ")     
@enduml