@startuml
title PUML example (manual)

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Container(JohnDoe, "John Doe")
Container(anotherserver, "another-server")
Container(aserver, "a-server")    
Rel_D(JohnDoe, anotherserver, "1. GET indirect-ping")
Rel_D(anotherserver, aserver, "2. GET ping")    
@enduml