@startuml
title PUML example (auto)
participant "John Doe"
participant "a-server"
"John Doe" -> "a-server": GET ping
activate "a-server"

"a-server" --> "John Doe": 200 OK
deactivate "a-server"
@enduml