@startuml
title Sequence diagram example: Ping test

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(JohnDoe, "John Doe")
Container(aserver, "a-server")    
Rel_D(JohnDoe, aserver, "1. GET ping ")    
@enduml